version: "3.9"
services:
  app:
    image: davidjj76/nodepop-api
    build: .
    container_name: app
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    volumes:
      - ./data:/home/node/app/data
      - ./${UPLOADS_FOLDER}:/home/node/app/${UPLOADS_FOLDER}
